//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Poco
{
    public partial class ModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=ModelContainer";
        public const string ContainerName = "ModelContainer";
    
        #region Constructors
    
        public ModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Restaurant> RestaurantJeu
        {
            get { return _restaurantJeu  ?? (_restaurantJeu = CreateObjectSet<Restaurant>("RestaurantJeu")); }
        }
        private ObjectSet<Restaurant> _restaurantJeu;
    
        public ObjectSet<Zone> ZoneJeu
        {
            get { return _zoneJeu  ?? (_zoneJeu = CreateObjectSet<Zone>("ZoneJeu")); }
        }
        private ObjectSet<Zone> _zoneJeu;
    
        public ObjectSet<Table> TableJeu
        {
            get { return _tableJeu  ?? (_tableJeu = CreateObjectSet<Table>("TableJeu")); }
        }
        private ObjectSet<Table> _tableJeu;
    
        public ObjectSet<Commande> CommandeJeu
        {
            get { return _commandeJeu  ?? (_commandeJeu = CreateObjectSet<Commande>("CommandeJeu")); }
        }
        private ObjectSet<Commande> _commandeJeu;
    
        public ObjectSet<Plat> PlatJeu1
        {
            get { return _platJeu1  ?? (_platJeu1 = CreateObjectSet<Plat>("PlatJeu1")); }
        }
        private ObjectSet<Plat> _platJeu1;
    
        public ObjectSet<Carte> CarteJeu
        {
            get { return _carteJeu  ?? (_carteJeu = CreateObjectSet<Carte>("CarteJeu")); }
        }
        private ObjectSet<Carte> _carteJeu;
    
        public ObjectSet<Notification> NotificationJeu
        {
            get { return _notificationJeu  ?? (_notificationJeu = CreateObjectSet<Notification>("NotificationJeu")); }
        }
        private ObjectSet<Notification> _notificationJeu;
    
        public ObjectSet<Commande1> Commande1Jeu
        {
            get { return _commande1Jeu  ?? (_commande1Jeu = CreateObjectSet<Commande1>("Commande1Jeu")); }
        }
        private ObjectSet<Commande1> _commande1Jeu;
    
        public ObjectSet<TypePlat> TypePlatJeu
        {
            get { return _typePlatJeu  ?? (_typePlatJeu = CreateObjectSet<TypePlat>("TypePlatJeu")); }
        }
        private ObjectSet<TypePlat> _typePlatJeu;
    
        public ObjectSet<Specialite> SpecialiteJeu
        {
            get { return _specialiteJeu  ?? (_specialiteJeu = CreateObjectSet<Specialite>("SpecialiteJeu")); }
        }
        private ObjectSet<Specialite> _specialiteJeu;
    
        public ObjectSet<Log> LogJeu
        {
            get { return _logJeu  ?? (_logJeu = CreateObjectSet<Log>("LogJeu")); }
        }
        private ObjectSet<Log> _logJeu;
    
        public ObjectSet<TypeNotification> TypeNotificationJeu
        {
            get { return _typeNotificationJeu  ?? (_typeNotificationJeu = CreateObjectSet<TypeNotification>("TypeNotificationJeu")); }
        }
        private ObjectSet<TypeNotification> _typeNotificationJeu;
    
        public ObjectSet<PlatEnCours> PlatEnCoursJeu
        {
            get { return _platEnCoursJeu  ?? (_platEnCoursJeu = CreateObjectSet<PlatEnCours>("PlatEnCoursJeu")); }
        }
        private ObjectSet<PlatEnCours> _platEnCoursJeu;
    
        public ObjectSet<Personne> PersonneJeu
        {
            get { return _personneJeu  ?? (_personneJeu = CreateObjectSet<Personne>("PersonneJeu")); }
        }
        private ObjectSet<Personne> _personneJeu;

        #endregion
    }
}
