//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Poco
{
    public partial class Cuisinier : Personne
    {
        #region Navigation Properties
    
        public virtual PlatEnCours PlatEnCours
        {
            get { return _platEnCours; }
            set
            {
                if (!ReferenceEquals(_platEnCours, value))
                {
                    var previousValue = _platEnCours;
                    _platEnCours = value;
                    FixupPlatEnCours(previousValue);
                }
            }
        }
        private PlatEnCours _platEnCours;

        #endregion
        #region Association Fixup
    
        private void FixupPlatEnCours(PlatEnCours previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Cuisinier, this))
            {
                previousValue.Cuisinier = null;
            }
    
            if (PlatEnCours != null)
            {
                PlatEnCours.Cuisinier = this;
            }
        }

        #endregion
    }
}
