//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Poco
{
    public partial class Manager : Personne
    {
        #region Primitive Properties
    
        public virtual int RestaurantID
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Restaurant Restaurant
        {
            get { return _restaurant; }
            set
            {
                if (!ReferenceEquals(_restaurant, value))
                {
                    var previousValue = _restaurant;
                    _restaurant = value;
                    FixupRestaurant(previousValue);
                }
            }
        }
        private Restaurant _restaurant;

        #endregion
        #region Association Fixup
    
        private void FixupRestaurant(Restaurant previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.Manager, this))
            {
                previousValue.Manager = null;
            }
    
            if (Restaurant != null)
            {
                Restaurant.Manager = this;
            }
        }

        #endregion
    }
}
