//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Poco
{
    public partial class Plat
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual double Prix
        {
            get;
            set;
        }
    
        public virtual int TypePlatID
        {
            get { return _typePlatID; }
            set
            {
                if (_typePlatID != value)
                {
                    if (TypePlat != null && TypePlat.ID != value)
                    {
                        TypePlat = null;
                    }
                    _typePlatID = value;
                }
            }
        }
        private int _typePlatID;
    
        public virtual int SpecialiteID
        {
            get { return _specialiteID; }
            set
            {
                if (_specialiteID != value)
                {
                    if (Specialite != null && Specialite.ID != value)
                    {
                        Specialite = null;
                    }
                    _specialiteID = value;
                }
            }
        }
        private int _specialiteID;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Commande> Commande
        {
            get
            {
                if (_commande == null)
                {
                    var newCollection = new FixupCollection<Commande>();
                    newCollection.CollectionChanged += FixupCommande;
                    _commande = newCollection;
                }
                return _commande;
            }
            set
            {
                if (!ReferenceEquals(_commande, value))
                {
                    var previousValue = _commande as FixupCollection<Commande>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCommande;
                    }
                    _commande = value;
                    var newValue = value as FixupCollection<Commande>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCommande;
                    }
                }
            }
        }
        private ICollection<Commande> _commande;
    
        public virtual TypePlat TypePlat
        {
            get { return _typePlat; }
            set
            {
                if (!ReferenceEquals(_typePlat, value))
                {
                    var previousValue = _typePlat;
                    _typePlat = value;
                    FixupTypePlat(previousValue);
                }
            }
        }
        private TypePlat _typePlat;
    
        public virtual Specialite Specialite
        {
            get { return _specialite; }
            set
            {
                if (!ReferenceEquals(_specialite, value))
                {
                    var previousValue = _specialite;
                    _specialite = value;
                    FixupSpecialite(previousValue);
                }
            }
        }
        private Specialite _specialite;
    
        public virtual ICollection<Carte> Carte
        {
            get
            {
                if (_carte == null)
                {
                    var newCollection = new FixupCollection<Carte>();
                    newCollection.CollectionChanged += FixupCarte;
                    _carte = newCollection;
                }
                return _carte;
            }
            set
            {
                if (!ReferenceEquals(_carte, value))
                {
                    var previousValue = _carte as FixupCollection<Carte>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarte;
                    }
                    _carte = value;
                    var newValue = value as FixupCollection<Carte>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarte;
                    }
                }
            }
        }
        private ICollection<Carte> _carte;

        #endregion
        #region Association Fixup
    
        private void FixupTypePlat(TypePlat previousValue)
        {
            if (previousValue != null && previousValue.Plat.Contains(this))
            {
                previousValue.Plat.Remove(this);
            }
    
            if (TypePlat != null)
            {
                if (!TypePlat.Plat.Contains(this))
                {
                    TypePlat.Plat.Add(this);
                }
                if (TypePlatID != TypePlat.ID)
                {
                    TypePlatID = TypePlat.ID;
                }
            }
        }
    
        private void FixupSpecialite(Specialite previousValue)
        {
            if (previousValue != null && previousValue.Plat.Contains(this))
            {
                previousValue.Plat.Remove(this);
            }
    
            if (Specialite != null)
            {
                if (!Specialite.Plat.Contains(this))
                {
                    Specialite.Plat.Add(this);
                }
                if (SpecialiteID != Specialite.ID)
                {
                    SpecialiteID = Specialite.ID;
                }
            }
        }
    
        private void FixupCommande(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Commande item in e.NewItems)
                {
                    if (!item.Plat.Contains(this))
                    {
                        item.Plat.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Commande item in e.OldItems)
                {
                    if (item.Plat.Contains(this))
                    {
                        item.Plat.Remove(this);
                    }
                }
            }
        }
    
        private void FixupCarte(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Carte item in e.NewItems)
                {
                    if (!item.Plat.Contains(this))
                    {
                        item.Plat.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Carte item in e.OldItems)
                {
                    if (item.Plat.Contains(this))
                    {
                        item.Plat.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
