//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Poco
{
    public partial class Specialite
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Nom
        {
            get;
            set;
        }
    
        public virtual string Image
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Plat> Plat
        {
            get
            {
                if (_plat == null)
                {
                    var newCollection = new FixupCollection<Plat>();
                    newCollection.CollectionChanged += FixupPlat;
                    _plat = newCollection;
                }
                return _plat;
            }
            set
            {
                if (!ReferenceEquals(_plat, value))
                {
                    var previousValue = _plat as FixupCollection<Plat>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlat;
                    }
                    _plat = value;
                    var newValue = value as FixupCollection<Plat>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlat;
                    }
                }
            }
        }
        private ICollection<Plat> _plat;
    
        public virtual ICollection<Carte> Carte
        {
            get
            {
                if (_carte == null)
                {
                    var newCollection = new FixupCollection<Carte>();
                    newCollection.CollectionChanged += FixupCarte;
                    _carte = newCollection;
                }
                return _carte;
            }
            set
            {
                if (!ReferenceEquals(_carte, value))
                {
                    var previousValue = _carte as FixupCollection<Carte>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCarte;
                    }
                    _carte = value;
                    var newValue = value as FixupCollection<Carte>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCarte;
                    }
                }
            }
        }
        private ICollection<Carte> _carte;

        #endregion
        #region Association Fixup
    
        private void FixupPlat(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Plat item in e.NewItems)
                {
                    item.Specialite = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Plat item in e.OldItems)
                {
                    if (ReferenceEquals(item.Specialite, this))
                    {
                        item.Specialite = null;
                    }
                }
            }
        }
    
        private void FixupCarte(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Carte item in e.NewItems)
                {
                    item.Specialite = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Carte item in e.OldItems)
                {
                    if (ReferenceEquals(item.Specialite, this))
                    {
                        item.Specialite = null;
                    }
                }
            }
        }

        #endregion
    }
}
