//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Poco
{
    public partial class TypeNotification
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual System.DateTime Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Notification Notification
        {
            get { return _notification; }
            set
            {
                if (!ReferenceEquals(_notification, value))
                {
                    var previousValue = _notification;
                    _notification = value;
                    FixupNotification(previousValue);
                }
            }
        }
        private Notification _notification;

        #endregion
        #region Association Fixup
    
        private void FixupNotification(Notification previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.TypeNotification, this))
            {
                previousValue.TypeNotification = null;
            }
    
            if (Notification != null)
            {
                Notification.TypeNotification = this;
            }
        }

        #endregion
    }
}
